DROP VIEW IF EXISTS widok_dziela_autorzy;
DROP VIEW IF EXISTS niezrealizowane_zamowienia_kupna;
DROP TABLE IF EXISTS wynajem_dzielo;
DROP TABLE IF EXISTS zamowienie_wynajem;
DROP TABLE IF EXISTS dziela_na_wystawie;
DROP TABLE IF EXISTS wystawa;
DROP TABLE IF EXISTS artysta_dzielo;
DROP TABLE IF EXISTS dzielo;
DROP TABLE IF EXISTS zamowienie_kupna;
DROP TABLE IF EXISTS typ_dziela;
DROP TABLE IF EXISTS artysta;
DROP TABLE IF EXISTS kurator;
DROP TABLE IF EXISTS klient;
DROP TABLE IF EXISTS galeria;
DROP TRIGGER IF EXISTS check_cena_trigger ON dzielo;
DROP FUNCTION IF EXISTS check_czy_dzielo_jest_na_sprzedaz();
DROP TRIGGER IF EXISTS check_wystawa_czy_dzielo_jest_dostepne ON dziela_na_wystawie;
DROP FUNCTION IF EXISTS check_wystawa_czy_dzielo_jest_dostepne();
DROP TRIGGER IF EXISTS check_wynajem_czy_dzielo_jest_dostepne ON wynajem_dzielo;
DROP FUNCTION IF EXISTS check_wynajem_czy_dzielo_jest_dostepne();
